"""initial models

Revision ID: 04467f362ca6
Revises: 
Create Date: 2026-06-29 20:43:39.395509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04467f362ca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price_mxn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('ml_user_id', sa.BigInteger(), nullable=True),
    sa.Column('ml_access_token', sa.Text(), nullable=True),
    sa.Column('ml_refresh_token', sa.Text(), nullable=True),
    sa.Column('ml_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ml_user_id')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('amount_mxn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=100), nullable=True),
    sa.Column('mp_status', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['credit_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_mlm', sa.String(length=20), nullable=True),
    sa.Column('new_mlm', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Índices para queries frecuentes
    op.create_index('ix_credit_transactions_user_id', 'credit_transactions', ['user_id'])
    op.create_index('ix_publications_user_id', 'publications', ['user_id'])
    op.create_index('ix_publications_status', 'publications', ['status'])

    # Vista de balance de créditos (PostgreSQL y SQLite compatible)
    op.execute("""
        CREATE VIEW user_credit_balance AS
        SELECT
            u.id AS user_id,
            COALESCE((
                SELECT SUM(ct.credits)
                FROM credit_transactions ct
                WHERE ct.user_id = u.id
                  AND ct.mp_status IN ('approved', 'trial')
                  AND (ct.expires_at IS NULL OR ct.expires_at > CURRENT_TIMESTAMP)
            ), 0)
            - COALESCE((
                SELECT SUM(p.credits_used)
                FROM publications p
                WHERE p.user_id = u.id AND p.status = 'published'
            ), 0)
            AS available_credits
        FROM users u
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS user_credit_balance")
    op.drop_index('ix_publications_status', table_name='publications')
    op.drop_index('ix_publications_user_id', table_name='publications')
    op.drop_index('ix_credit_transactions_user_id', table_name='credit_transactions')
    op.drop_table('publications')
    op.drop_table('credit_transactions')
    op.drop_table('users')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
